<a href="https://colab.research.google.com/github/Duks31/google-colab-code/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import tensorflow as tf

In [20]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [21]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28, 28)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [22]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.28975835,  0.09281549, -0.9486324 , -0.43243802,  0.22236463,
         0.09741817,  0.10479341,  0.19289258, -0.35649762,  0.08207411]],
      dtype=float32)

In [23]:
tf.nn.softmax(predictions).numpy()

array([[0.13455503, 0.11050164, 0.03900081, 0.06535127, 0.12578568,
        0.11101142, 0.11183317, 0.12213261, 0.07050737, 0.10932106]],
      dtype=float32)

In [24]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True)

In [25]:
loss_fn(y_train[:1], predictions).numpy()


2.1981223

In [26]:
model.compile(optimizer= 'adam', 
              loss = loss_fn, 
              metrics = ['accuracy'])


In [27]:
model.fit(x_train, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2907 - accuracy: 0.9153
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1395 - accuracy: 0.9588
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1038 - accuracy: 0.9682
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0851 - accuracy: 0.9736
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0736 - accuracy: 0.9770


In [28]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0717 - accuracy: 0.9790 - 1s/epoch - 3ms/step


[0.07173135131597519, 0.9789999723434448]

In [29]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [30]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.5350177e-07, 2.6529429e-07, 3.6996146e-06, 7.2370764e-05,
        2.7462052e-11, 4.4535713e-07, 3.1079341e-13, 9.9990690e-01,
        2.2358358e-06, 1.3568696e-05],
       [6.8776478e-09, 5.1192983e-05, 9.9994421e-01, 1.1712347e-06,
        2.2079114e-15, 1.1512254e-07, 1.9978322e-06, 3.2306486e-12,
        1.2441348e-06, 1.2992789e-12],
       [2.7669188e-07, 9.8835480e-01, 1.4923946e-03, 2.7738646e-05,
        4.8614782e-04, 1.8513094e-05, 8.6629771e-05, 8.3351489e-03,
        1.1967564e-03, 1.6057579e-06],
       [9.9999070e-01, 4.4089804e-10, 6.8305153e-06, 9.7183408e-09,
        7.3882248e-08, 1.2538193e-06, 4.5896957e-07, 6.1833128e-07,
        7.5573237e-10, 1.4307702e-07],
       [1.0611689e-05, 1.5404688e-11, 1.6572346e-06, 6.5866255e-09,
        9.9730825e-01, 3.1987523e-07, 1.1657634e-06, 3.2979289e-05,
        1.4204842e-07, 2.6449293e-03]], dtype=float32)>