<a href="https://colab.research.google.com/github/Duks31/google-colab-code/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print("tensorflow version: ", tf.__version__)

tensorflow version:  2.11.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 2s 0us/step


In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28, 28)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.18305597,  0.44382173, -0.14047399, -0.49903053, -0.7371118 ,
         0.47712487, -0.9981567 ,  0.2794078 , -0.6047678 ,  0.6028681 ]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.11558068, 0.15001489, 0.08363305, 0.05843308, 0.04605338,
        0.15509498, 0.03547244, 0.12727125, 0.05256997, 0.1758763 ]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()


1.8637176

In [ ]:
model.compile(optimizer= 'adam', 
              loss = loss_fn, 
              metrics = ['accuracy'])


In [ ]:
model.fit(x_train, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 8s 3ms/step - loss: 0.2978 - accuracy: 0.9137
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1433 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1080 - accuracy: 0.9669
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0883 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0762 - accuracy: 0.9759


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0680 - accuracy: 0.9795 - 1s/epoch - 3ms/step


[0.06800216436386108, 0.9794999957084656]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.14884756e-07, 1.05934896e-08, 1.60688376e-06, 1.29613938e-04,
        2.08242863e-12, 4.42736280e-07, 4.09694463e-15, 9.99863982e-01,
        6.81200561e-07, 3.54107124e-06],
       [3.53162591e-07, 3.14094032e-05, 9.99923944e-01, 3.12813268e-06,
        1.53583410e-15, 4.07583102e-05, 4.52770109e-07, 1.17940531e-12,
        5.14655021e-08, 5.17463121e-16],
       [4.85621115e-07, 9.98434246e-01, 5.97985403e-04, 6.97522410e-06,
        4.17753399e-05, 1.85174179e-06, 1.11694353e-05, 6.79528515e-04,
        2.23548763e-04, 2.40343593e-06],
       [9.99770343e-01, 8.56441496e-09, 2.08031866e-04, 2.79890219e-06,
        3.04393183e-07, 2.77973618e-06, 8.43581859e-07, 5.55168663e-06,
        1.00643591e-08, 9.25336190e-06],
       [7.78565891e-07, 3.99669992e-10, 2.40367012e-06, 1.10744045e-08,
        9.97906923e-01, 1.13961093e-07, 1.65288242e-07, 4.86827266e-05,
        1.36254289e-06, 2.03955593e-03]], dtype=float32)>